AllCops:
  NewCops: enable
  Exclude:
    - Gemfile
    - bin/bundle
    - bin/rails
    - bin/rake
    - db/schema.rb
    - config/application.rb
    - lib/tasks/auto_annotate_models.rake

Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Metrics/AbcSize:
  Max: 32

Metrics/BlockLength:
  Max: 32
  Exclude:
    - spec/**/*.rb

Metrics/ClassLength:
  Max: 100

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/MethodLength:
  Max: 20
  Exclude:
    - db/migrate/*.rb

Metrics/PerceivedComplexity:
  Max: 12

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/BlockComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/GuardClause:
  MinBodyLength: 10

Style/Lambda:
  EnforcedStyle: literal

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
